# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Ohjelmistotuotanto 2021
email: matti.luukkainen@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" 
url: "https://ohjelmistotuotanto-hy.github.io" 
github_username:  mluukkai
repo_url: "https://github.com/ohjelmistotuotanto-hy/ohjelmistotuotanto-hy.github.io"
repo_branch: "master"
stats_url: "https://study.cs.helsinki.fi/stats/courses/ohtu2021"

python_exercise_repo_url: "https://github.com/ohjelmistotuotanto-hy/syksy2021-python"
java_exercise_repo_url: "https://github.com/ohjelmistotuotanto-hy/syksy2021-java"

moniv-dl:
  - "FAIL"
  - "sunnuntai 7.11. klo 23:59:00"
  - "sunnuntai 14.11. klo 23:59:00"
  - "sunnuntai 21.11. klo 23:59:00"
  - "sunnuntai 28.11. klo 23:59:00"
  - "sunnuntai 5.12. klo 23:59:00"
  - "sunnuntai 12.12. klo 23:59:00"
  - "sunnuntai 19.12. klo 23:59:00"

lask-dl:
  - "FAIL"
  - "maanantai 8.11. klo 23:59"
  - "maanantai 15.11. klo 23:59" 
  - "maanantai 22.11. klo 23:59"
  - "maanantai 29.11. klo 23:59"
  - "maanantai 6.12. klo 23:59"
  - "maanantai 13.12. klo 23:59"
  - "maanantai 20.12. klo 23:59"

luennot:
  - "FAIL"
  - "maanantai 1.11. klo 12-14"
  - "tiistai 2.11. klo 12-14"
  - "maanantai 8.11. klo 12-14"
  - "tiistai 9.11. klo 12-14"
  - "maanantai 15.11. klo 12-14"
  - "tiistai 16.11. klo 12-14"  
  - "maanantai 22.11. klo 12-14"
  - "tiistai 23.11. klo 12-14"
  - "maanantai 29.11. klo 12-14"
  - "tiistai 30.11. klo 12-14"  

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
