# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Ohjelmistotuotanto 2021
email: matti.luukkainen@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" 
url: "https://ohjelmistotuotanto-hy.github.io" 
github_username:  mluukkai
repo_url: "https://github.com/ohjelmistotuotanto-hy/ohjelmistotuotanto-hy.github.io"
repo_branch: "master"
stats_url: "https://study.cs.helsinki.fi/stats/courses/ohtu2021"

dl1_m: "sunnuntai 7.11. klo 23:59:00"
dl1_l: "maanantai 8.11. klo 23:59"

dl2_m: "sunnuntai 14.11. klo 23:59:00"
dl2_l: "maanantai 15.11. klo 23:59"

dl3_m: "sunnuntai 21.11. klo 23:59:00"
dl3_l: "maanantai 22.11. klo 23:59"

dl4_m: "sunnuntai 28.11. klo 23:59:00"
dl4_l: "maanantai 29.11. klo 23:59"

dl5_m: "sunnuntai 5.12. klo 23:59:00"
dl5_l: "maanantai 6.12. klo 23:59"

dl6_m: "sunnuntai 12.12. klo 23:59:00"
dl6_l: "maanantai 13.12. klo 23:59"

dl7_m: "sunnuntai 19.12. klo 23:59:00"
dl7_l: "maanantai 20.12. klo 23:59"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
