# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Ohjelmistotuotanto 2022
email: matti.luukkainen@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: ''
url: 'https://ohjelmistotuotanto-hy.github.io'
github_username: mluukkai
repo_url: 'https://github.com/ohjelmistotuotanto-hy/ohjelmistotuotanto-hy.github.io'
repo_branch: 'master'
stats_url: 'https://study.cs.helsinki.fi/stats/courses/ohtu2022'

python_exercise_repo_url: 'https://github.com/ohjelmistotuotanto-hy/syksy2022-python'
java_exercise_repo_url: 'https://github.com/ohjelmistotuotanto-hy/syksy2021-java'

moniv-dl:
  - 'FAIL'
  - 'sunnuntai 6.11. klo 23:59:00'
  - 'sunnuntai 13.11. klo 23:59:00'
  - 'sunnuntai 20.11. klo 23:59:00'
  - 'sunnuntai 27.11. klo 23:59:00'
  - 'sunnuntai 4.12. klo 23:59:00'
  - 'perjantai 23.12. klo 23:59:00'
  - 'perjantai 23.12. klo 23:59:00'

lask-dl:
  - 'FAIL'
  - 'maanantai 7.11. klo 23:59'
  - 'maanantai 14.11. klo 23:59'
  - 'maanantai 21.11. klo 23:59'
  - 'maanantai 28.11. klo 23:59'
  - 'tiistai 6.12. klo 23:59'
  - 'maanantai 12.12. klo 23:59'
  - 'perjantai 23.12. klo 23:59'

luennot:
  - 'FAIL'
  - 'maanantai 31.10. klo 12-14'
  - 'tiistai 1.11. klo 12-14'
  - 'maanantai 7.11. klo 12-14'
  - 'tiistai 8.11. klo 12-14'
  - 'maanantai 14.11. klo 12-14'
  - 'tiistai 15.11. klo 12-14'
  - 'maanantai 21.11. klo 12-14'
  - 'tiistai 22.11. klo 12-14'
  - 'maanantai 28.11. klo 12-14'
  - 'tiistai 28.11. klo 12-14'
  - 'maanantai 5.12. klo 12-14'
  - 'maanantai 12.12. klo 12-14'
  - 'tiistai 13.12. klo 12-14'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
